### ISSUE TITLE
remove compiled files from repo for easy updating

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-angular-frontend#22]
trying to update i continuously run into trouble with the minified and compiled versions of:

/dist/web/css/piecemeta-angular-frontend.cc
/dist/web/js/piecemeta-angular-*.js

because they are rebuilt locally after update and then are "changed".

**Comment by dasantonym** [comment]
i initially added them to be able to just pull the repo and run the static web frontend without having node and grunt ready to build it. this might be more of an issue with the update script i supplied.

for the vm the best would just be a

```
git fetch --all
git reset --hard origin/master
```

instead of the `git pull origin/master`

i could also remove the compiled files and add them as a "binary", but i'd need to remember updating this on each new release then...

**Comment by dasantonym** [comment]
wontfix, not an issue with the repo, just the updater was shitty... i'll keep compiled files in the dist folder
