### ISSUE TITLE
Gruntfile.js > nodewebkit > client > options > platforms : linux???

### ISSUE THREAD

**Issue by denjello** [PieceMeta/piecemeta-angular-frontend#23]
will this build on debian?

```
nodewebkit: {
            client: {
                options: {
                    platforms: ['osx64'],
                    version: '0.12.0',
                    buildDir: './build/nw',
                    macPlist: {
                        'NSHumanReadableCopyright': "2015 PieceMeta"
                    }
                },
                src: ['./dist/nw/**/*']
            }
        }
```

**Comment by denjello** [comment]
or would this be more appropriate?

`platforms: ['win', 'osx', 'linux']`

(according to the docs it should build 32 & 64bit versions...)

**Comment by dasantonym** [comment]
yes it should build on all systems, but there are extra steps necessary for each platform and each architecture. since the osc module references dependencies with native code, those modules need to be rebuilt including the node-webkit headers. this is not done automatically and it might be nice to include these steps in the grunt file. still, building all on one machine would require cross-compiling.

see: https://github.com/nwjs/nw-gyp

**Comment by dasantonym** [comment]
this is now referenced in the readme
