### ISSUE TITLE
do not load streams on package/xxx/show

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-angular-frontend#24]
… takes too long for any package containing more that short test data sets. i think the viz should maybe go on it's own page as it would anyways make much more sense to be able to choose what to look at.

… and along that route. standard viz's could be cached as svg / image for speedy previews.

**Comment by dasantonym** [comment]
i hope to close this with the fix for #14 

the viz actually already doesn't get a lot of data and it is always quantized to never show all frames, so it normally does not hurt the page. the controller just stupidly loads every single number there is and that can take ages.

caching would be nice but it's a can of worms i'll save for later...

**Comment by dasantonym** [comment]
this should work now with the latest commit. it only starts to load frame data when selecting channels to view. and it no longer loads everything, just the stuff it'll actually show.
