### ISSUE TITLE
add delete next to save button on edit pages

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-angular-frontend#6]
… and maybe have it confirm before doing it's thing

**Comment by denjello** [comment]
RANT WARNING

Personally, I thing confirming is an anti-pattern. Rage-clicking and drunk-users double click and ignore warnings, if they can even read in the first place.

I prefer undo logic because it retains data state / scope. Here is a good read about the issue:
http://alistapart.com/article/neveruseawarning

**Comment by dasantonym** [comment]
you're absolutely right (also alistapart, as usual). i'll remove the warning stuff altogether and for recovery/undo i'll add a trashcan instead. but that takes time and in the meantime: happy drunk deleting, har har!

**Comment by dasantonym** [comment]
delete just got less crappy with proper buttons and functionality. confirmation is still the mode of operation. the trashcan thing will get a bit complex because of related items. so this is non critical to me in light of other bugs and improvements.
